### ISSUE TITLE
OGPがありません

### ISSUE THREAD

**Issue by TetsuakiBaba** [ia-itlab/tmu-ia-site#35]
OGP設定を追加したい。

**Comment by mt-sumikko** [comment]
【slack通知テスト】この件周知しました、前期中には対処する

**Comment by mt-sumikko** [comment]
【slack通知テスト】この件周知しました、前期中には対処する

**Comment by mt-sumikko** [comment]
各studioやvoicesはそのページを代表する画像が出るのが理想かもしれない🤔
https://reiwinn-web.net/2017/04/07/ogp_php/

**Comment by TetsuakiBaba** [comment]
ia ウェブの構造的に、OGPを動的に生成しなくても、それぞれの該当する html ファイルに直接記述しちゃうのでOKです。

**Comment by mt-sumikko** [comment]
対処したのでクローズします
