### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by TetsuakiBaba** [ia-itlab/tmu-ia-site#43]
ulcc.min.css, ulcc.min.jsファイルにアクセスできなくなりました。

**Comment by mt-sumikko** [comment]
mainブランチでアップロード→GTMの設定を書き換えました、サーバーに反映お願いいたします。

**Comment by TetsuakiBaba** [comment]
更新はしましたが、まだcssの参照でエラーが残ってます。

**Comment by mt-sumikko** [comment]
GTMの方パスミスしてました、修正完了しています。

**Comment by mt-sumikko** [comment]
無事治ったので閉じます

**Comment by TetsuakiBaba** [comment]
close #43
